version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: admin-panel-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: ${JWT_EXPIRES_IN}
      API_VERSION: ${API_VERSION}
      API_PREFIX: ${API_PREFIX}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      GEMINI_MODEL: ${GEMINI_MODEL}
      GEMINI_TEMPERATURE: ${GEMINI_TEMPERATURE}
      GEMINI_TRIGGER_TOKENS: ${GEMINI_TRIGGER_TOKENS}
      GEMINI_TARGET_TOKENS: ${GEMINI_TARGET_TOKENS}
      GEMINI_VOICE_NAME: ${GEMINI_VOICE_NAME}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URI: ${GOOGLE_REDIRECT_URI}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY}
      RECORDINGS_DIRECTORY: ${RECORDINGS_DIRECTORY}
    ports:
      - "3003:3000"
    volumes:
      - ./recordings:/app/recordings
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 