version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: admin-panel-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 24h
      API_VERSION: v1
      API_PREFIX: /api
    ports:
      - "3003:3000"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge 