version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: admin-panel-postgres
    environment:
      POSTGRES_DB: admin_panel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: admin-panel-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/admin_panel
      JWT_SECRET: ${JWT_SECRET}
      JWT_EXPIRES_IN: 24h
      API_VERSION: v1
      API_PREFIX: /api
    ports:
      - "3003:3000"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge 